apiVersion: v1
kind: Service
metadata:
  name: kiwitcms-service
  namespace: kiwitcms
spec:
  selector:
    app: kiwitcms
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
